[project]
name = "wazobia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "syncXL", email = "xlegend1251@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "datasets>=5.0.1",
    "fire>=0.7.1",
    "huggingface>=0.0.1",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "librosa>=1.0.0",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "polars>=1.44.2",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "ray[data]>=2.58.0",
    "soundfile>=0.14.0",
    "torch>=2.14.0",
    "torchcodec>=0.16.0",
    "transformers>=5.17.0",
    "unidecode>=1.4.0",
]

[project.scripts]
wazobia = "wazobia:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
